### ISSUE TITLE
share the trained model

### ISSUE THREAD

**Issue by monkeyshichi** [zhengye1995/DCIC19-Rebar-detection-Rank2#2]
can you share the trained model?  For now I can't train this model for limited gpu memory,when I train new model,i can compare them.I will be very grateful.

**Comment by zhengye1995** [comment]
Sorry, this competition has been over for more than a year so I do not keep this weight. You can evaulte the result with f1-score, the IOU threshold is 0.7. I got 0.992 f1-score in test dataset under this metric.

**Comment by monkeyshichi** [comment]
got it .Thanks
